server:
  port: 8082
spring:
  application:
    name: billing-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.102.125.29:8848
        group: sz
management:
  endpoints:
    web:
      exposure:
        include: '*'
