server:
  port: 8071
spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 121.196.245.235:8848
        group: sz

management:
  endpoints:
    web:
      exposure:
        include: '*'

order-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
stock-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
billing-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

logging:
  level:
    org:
      kzhou:
        user:
          feign:
            OrderServiceFeignApi: debug
            StockServiceFeignApi: debug
feign:
  client:
    config:
      default:
        connectTimeout: 5000 #连接超时
        readTimeout: 5000 #处理超时
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
