server:
  port: 8081
spring:
  application:
    name: billing-service
  cloud:
    nacos:
      discovery:
        server-addr: 121.196.245.235:8848
        group: sz
management:
  endpoints:
    web:
      exposure:
        include: '*'
