server:
  port: 8061
spring:
  application:
    name: stock-service
  cloud:
    nacos:
      discovery:
        server-addr: 121.196.245.235:8848
        group: sz

management:
  endpoints:
    web:
      exposure:
        include: '*'
